import type { Metadata } from "next";
import "./globals.css";
import NavBar from "../components/navbar/NavBar";
import Footer from "../components/footer/Footer";

import { Poppins } from "next/font/google";

const PoppinsFont = Poppins({
	subsets: ["latin"],
	weight: "600"
});

export const metadata: Metadata = {
	title: "Portifólio",
	description: "Generated by create next app"
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={PoppinsFont.className}>
				<div className="container">
					<NavBar></NavBar>
					{children}
				</div>
				<Footer></Footer>
			</body>
		</html>
	);
}
